### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by vpeschenkov** [smalam119/live-news-viper#2]
@smalam119 Hi! I've tried to build this project but found that Xcode can't find the next file: `LiveNewsRouter.swift`. It is in the folder, but it would be better to add it to the .xcodeproj file though. So I would fix it, but I've found that you don't use a `.gitignore` file. Also, I've got a lot of changed/created files just by opening the project; without any changes:

![](https://i.imgur.com/F3PRHaO.png)

It would be better to add a `.gitignore` file to this project. You can find one [there](https://github.com/github/gitignore/blob/master/Swift.gitignore) .

**Comment by anirudhamahale** [comment]
Mean while you can use [this repo ](https://github.com/anirudhamahale/live-news-viper)
Though I have created pull request for that issue.

**Comment by smalam119** [comment]
thanks anirudhamahale for addressing the issue. I believe it is sorted now. Thanks.
