### ISSUE TITLE
LiveNewsRouter.swift file not found

### ISSUE THREAD

**Issue by prasads** [smalam119/live-news-viper#5]
I am unable to find livenewrouterfile.swift

**Comment by Banck** [comment]
Hello!
There is LiveNewsRouter.swift file in the folder. So to resolve this issue you can simply remove old reference from xcode and add LiveNewsRouter.swift from /Live News/modules/route to xcode structure:
![image](https://user-images.githubusercontent.com/6259254/42070468-bdf03298-7b80-11e8-9959-ca6338b8c30e.png)

**Comment by smalam119** [comment]
I believe Banck provided the solution. So I am closing the issue. Thanks.
